// All user-facing text lives here (one place to change or translate).
export const t = {
  title: 'History of Europe on a map',
  year: 'Year',
  pin: 'Pin',
  mode: 'Mode',
  present: 'present',
  approximate: '(approximate)',
  rewind: 'Rewind',
  allView: 'All',
  older: 'Older period',
  newer: 'Newer period',
  play: 'Play',
  pause: 'Pause',
  syncYear: 'Show the map of that year',
  loadingPeriods: 'Loading…',
  loadingMore: 'loading earlier periods…',
  loadMoreFailed: 'Could not load more periods.',
  retry: 'Retry',
  coordsPlaceholder: 'lat, lon',
  coordsGo: 'Go',
  coordsError: 'Enter coordinates like 54.35, 18.65',
  lackOfData: 'Lack of data',
  bc: 'BC',
  inYear: (year: string) => `In ${year}`,
  closestMap: (year: string) => `Closest available map: ${year}`,
  noDataYear: 'No data for this place in this year.',
  noData: 'No data for this place.',
  placeHistory: 'History of this place',
  noImportedData: 'no data — run the import',
  serverUnreachable: 'Could not reach the server. Retrying…',
  loadFailed: 'Could not load data. Try clicking again.',
};
